# Change these first
owner: LoQqvEe # Your GitHub organization or username, where this repository lives
repo: loqq-upptime # The name of this repository

sites:
  - name: OrcaBOT - Website
    url: https://orcabot.in.th

status-website:
  cname: status.orcabot.in.th
  # baseUrl: /loqq-upptime
  logoUrl: https://i.imgur.com/rrf3Z4C.png
  name: LoQ - Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Hello!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
